<?php
#Значения типа, определения, внут. авторитета стратегии и основы
$ru_eng = array(
'манифестирующий генератор' => 'manifesting generator' ,
'генератор' => 'generator',
'рефлектор' => 'reflector',
'манифестор' => 'manifestor',
'проектор' => 'projector',
'одиночное' => 'single definition',
'двойное' => 'split definition',
'тройное' => 'triple definition',
'тройное' => 'triple split definition',
'четыре определения' => 'quadruple definition',
'нет определения' => 'no definition',
'нет' => 'none',
'сакрал' => 'sacral',
'эмоциональный' => 'emotional',
'эмоциональный' => 'emotional - solar plexus',
'селезеночный' => 'splenic',
'эго' => 'ego',
'чистый проектор' => 'self projected',
'откликаться' => 'to respond',
'ждать приглашения' => 'wait for the invitation',
'ждать окончания цикла луны' => 'wait a lunar cycle',
'информировать' => 'to inform',
'ложное я' => 'not self theme',
'фрустрация' => 'frustration',
'разочарование' => 'disappointment',
'озлобленность' => 'bitterness',
'гнев' => 'anger'
);

#значения информационного креста
$cross_en = array ('right angle cross of', 'juxtaposition cross of', 'left angle cross of');
$cross_ru = array ('правоугольный крест', 'крест джакстопозиции', 'левоугольный крест');

/*в массиве $cross_en_det находится заменяемы текст, в массиве $cross_ru_det замещающий*/
$cross_en_det = array(
/*правоугольный крест*/
'sphinx',
'laws',
'explanation',
'consciousness',
'eden',
'contagen',
'planning',
'vessel of love',
'service',
'four ways',
'sleeping phoenix',
'tension',
'rulership',
'unexpected',
'maya',
'penetration',
'contagion',
/*крест джакстопозиции*/
'driver',
'mutation',
'formulization',
'habits',
'conflict',
'interaction',
'contribution',
'focus',
'behaviour',
'ideas',
'articulation',
'listening',
'empowering',
'extremes',
'experimentation',
'opinions',
'correction',
'need',
'now',
'control',
'grace',
'assimilation',
'rationalization',
'innocence',
'trickster',
'caring',
'risks',
'commitment',
'fates',
'influence',
'conservation',
'retreat',
'power',
'experience',
'crisis',
'bargains',
'opposition',
'provocation',
'denal',
'fantasy',
'completion',
'insight',
'alertness',
'possession',
'serendipity',
'oppression',
'depth',
'principles',
'values',
'shock',
'stillness',
'beginnings',
'ambition',
'moods',
'stimulation',
'intuition',
'vitality',
'strategy',
'limitation',
'thinking',
'detail',
'doubts',
'confusion',
/*Левоугольный крест*/
'defiace',
'defiance',
'wishes',
'revolution',
'separation',
'plane',
'masks',
'uncertainty',
'indententification',
'prevention',
'education',
'ancertainty',
'prevention',
'identification',
'upheavel',
'refinement',
'duality',
'endevour',
'informing',
'dedication',
'incanation',
'incarnation',
'healing',
'confrontation',
'alignment',
'industry',
'alpha',
'limitation',
'refinement',
'duality',
'plane',
'migration',
'individualism',
'endevour',
'clarion',
'demands',
'cycles',
'spirit',
'distraction',
'obscuration',
'dominion',
'endeavor'
);
$cross_ru_det = array(
/*правоугольный крест*/
'сфинкса',
'законов',
'объяснения',
'осознанности',
'рая',
'инфицирования',
'планирования',
'сосуда любви',
'служения',
'четырех путей',
'спящего феникса',
'напряжения',
'руководства',
'неожиданного',
'майя',
'проникновения',
'инфекции',
/*крест джакстопозиции*/
'водителя',
'мутации',
'формулирования',
'привычек',
'конфликта',
'взаимодействия',
'вклада',
'фокуса',
'поведения',
'идей',
'артикуляци',
'слушания',
'придания силы',
'крайностей',
'экспериментирования',
'мнений',
'исправления',
'нужды',
'сейчас',
'контроля',
'грации',
'уподобления',
'рационализации',
'невинности',
'обманщика',
'заботы',
'риска',
'обязательства',
'судеб',
'влияния',
'сохранения',
'ретрита',
'силы',
'опыта',
'кризиса',
'сделок',
'оппозиции',
'провокации',
'отречения',
'фантазии',
'завершения',
'озарения',
'бдительности',
'обладания',
'обстоятельств',
'угнетенности',
'глубины',
'принципов',
'ценности',
'шока',
'спокойствия',
'начинаний',
'амбиций',
'настроения',
'стимуляции',
'интуиции',
'жизненности',
'стратегии',
'ограничения',
'мышления',
'детали',
'сомнений',
'замешательства',
/*Левоугольный крест*/
'неповиновения',
'сопротивления ',
'желаний',
'революции',
'разделения',
'плана',
'масок',
'не уверенности',
'идентификации',
'предупреждени',
'образования',
'неуверенности',
'предотвращения',
'идентификации',
'переворота',
'очищения',
'дуальности',
'усилия',
'информирования',
'преданности',
'инкарнации',
'инкарнации',
'исцеления',
'конфронтации',
'выравнивания',
'усилия',
'альфы',
'ограничения',
'очищения',
'дуальности',
'плана',
'миграции',
'индивидуализма',
'старания',
'горна',
'требований',
'циклов',
'духа',
'отвлечения',
'затмения',
'господства',
'усиления'
);
?>